image: Visual Studio 2022

configuration:
  - Release

before_build:
  - dotnet restore
  - choco install opencover.portable
  - choco install codecov

test_script:
  - dotnet test --logger "console;verbosity=detailed"
  - OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test -filter:"+[NokitaKaze.PedersenHashNet*]* -[*.Test]* -[BlakeSharp*]*" -output:".\MyProject_coverage.xml" -oldstyle --short-test

after_test:
  - codecov -f "MyProject_coverage.xml"
